name: Image CI Latest - MultiPlatform

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: tetragon
            dockerfile: ./Dockerfile

          - name: tetragon-operator
            dockerfile: ./operator.Dockerfile

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Getting image tag
        id: tag
        run: |
          # GITHUB_REF is set to "refs/heads/$branch" for branches and "refs/tags/$tag" for tags.
          echo ::set-output name=tag::$(basename "$GITHUB_REF")
          echo ::set-output name=shortSHA::$(git rev-parse --short HEAD)

      - name: Checkout Source Code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release Build ${{ matrix.name }}
        uses: docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935
        id: docker_build_release
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            dockerhub.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:latest


